# Generated by Django 5.2.1 on 2025-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashprice',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trashprice',
            name='poin_per_kg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
