name: eco_trash
description: "A new Flutter project."

publish_to: 'none'  # Hapus baris ini jika kamu ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0
  provider: ^6.1.1
  go_router: ^6.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/top_background.png
    - assets/facebook.png
    - assets/google.png
    - assets/ic_notification.xml
    - assets/ic_profile.xml
    - assets/outline_add_chart_24.xml
    - assets/outline_delete_24.xml
    - assets/baseline_info_outline_24.xml
    - assets/ic_price.xml
